name: explorando_clima_app
description: Explorando Nuvens - Guia de Identificação

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  http: any
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  carousel_slider: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

